name: Publish to ECR

on: pull_request

jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-22.04
    steps:
      - name: Build and push to ECR
        uses: citizensadvice/build-and-push-action@206bf7dfb5d0201183fb0de81dc4913334c4527e
        with:
          aws_access_key: ${{ secrets.PUBLIC_PUSH_ECR_AWS_KEY }}
          aws_secret_key: ${{ secrets.PUBLIC_PUSH_ECR_AWS_SECRET }}
          dockerfile_context: '.'
          repository_name: clamav-mock
          multiarch_build: 'enabled'
          auth_token: ${{ secrets.GITHUB_TOKEN }}
