name: Run linting

on: workflow_call

jobs:
  lint:
    name: Lint
    runs-on: runs-on,run-id=${{ github.run_id }},job=lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735
        with:
          bundler-cache: true
      - run: bundle exec rubocop