name: Run linting

on: workflow_call

jobs:
  lint:
    name: Lint
    runs-on: runs-on,run-id=${{ github.run_id }},job=lint
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073
        with:
          bundler-cache: true
      - run: bundle exec rubocop