name: Run linting

on: workflow_call

jobs:
  lint:
    name: Lint
    runs-on: runs-on,run-id=${{ github.run_id }},job=lint
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74
        with:
          bundler-cache: true
      - run: bundle exec rubocop