# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
# https://github.com/ruby/setup-ruby

name: Run tests

on: workflow_call

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
