# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
# https://github.com/ruby/setup-ruby

name: Test and lint

on:
  pull_request:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
